/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pmem_pmemkv_KVTree */

#ifndef _Included_io_pmem_pmemkv_KVTree
#define _Included_io_pmem_pmemkv_KVTree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pmem_pmemkv_KVTree
 * Method:    kvtree_open
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_io_pmem_pmemkv_KVTree_kvtree_1open
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     io_pmem_pmemkv_KVTree
 * Method:    kvtree_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pmem_pmemkv_KVTree_kvtree_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pmem_pmemkv_KVTree
 * Method:    kvtree_get
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_pmem_pmemkv_KVTree_kvtree_1get
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_pmem_pmemkv_KVTree
 * Method:    kvtree_put
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_pmem_pmemkv_KVTree_kvtree_1put
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     io_pmem_pmemkv_KVTree
 * Method:    kvtree_remove
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_pmem_pmemkv_KVTree_kvtree_1remove
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_pmem_pmemkv_KVTree
 * Method:    kvtree_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_pmem_pmemkv_KVTree_kvtree_1size
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
