/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pmem_pmemkv_Database_Builder */

#ifndef _Included_io_pmem_pmemkv_Database_Builder
#define _Included_io_pmem_pmemkv_Database_Builder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pmem_pmemkv_Database_Builder
 * Method:    config_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_pmem_pmemkv_Database_00024Builder_config_1new
  (JNIEnv *, jobject);

/*
 * Class:     io_pmem_pmemkv_Database_Builder
 * Method:    config_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pmem_pmemkv_Database_00024Builder_config_1delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pmem_pmemkv_Database_Builder
 * Method:    config_put_int
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_io_pmem_pmemkv_Database_00024Builder_config_1put_1int
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     io_pmem_pmemkv_Database_Builder
 * Method:    config_put_string
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_pmem_pmemkv_Database_00024Builder_config_1put_1string
  (JNIEnv *, jobject, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
